-- 코드를 입력하세요
SELECT FR.PRODUCT_ID, FR.PRODUCT_NAME, SUM(FO.AMOUNT*FR.PRICE) TOTAL_SALES
FROM FOOD_PRODUCT  FR
INNER JOIN FOOD_ORDER  FO
ON FR.PRODUCT_ID = FO.PRODUCT_ID
WHERE FO.PRODUCE_DATE LIKE '2022-05%'
GROUP BY FR.PRODUCT_ID 
ORDER BY 3 DESC, 1  