-- 코드를 입력하세요
SELECT BK.BOOK_ID,AH.AUTHOR_NAME,DATE_FORMAT(BK.PUBLISHED_DATE,"%Y-%m-%d") AS PUBLISHED_DATE
FROM BOOK BK
INNER JOIN AUTHOR AH
ON BK.AUTHOR_ID = AH.AUTHOR_ID
WHERE BK.CATEGORY LIKE '경제'
ORDER BY BK.PUBLISHED_DATE;