-- 코드를 입력하세요
SELECT BK.CATEGORY , SUM(BS.SALES) TOTAL_SALES
FROM BOOK BK
INNER JOIN BOOK_SALES BS
ON BK.BOOK_ID = BS.BOOK_ID
WHERE BS.SALES_DATE LIKE '2022-01%'
GROUP BY BK.CATEGORY
ORDER BY BK.CATEGORY;