-- 코드를 입력하세요
SELECT YEAR(OS.SALES_DATE) AS YEAR ,MONTH(OS.SALES_DATE) AS MONTH,UI.GENDER AS GENDER , COUNT(DISTINCT(UI.USER_ID)) AS USERS 
FROM USER_INFO  UI
INNER JOIN ONLINE_SALE OS
ON UI.USER_ID = OS.USER_ID
AND UI.GENDER IS NOT NULL
GROUP BY MONTH(OS.SALES_DATE) , UI.GENDER
ORDER BY 1,2,3;