-- 코드를 입력하세요
SELECT PD.PRODUCT_CODE, (PD.PRICE * SUM(OS.SALES_AMOUNT)) AS SALES
FROM PRODUCT PD
INNER JOIN OFFLINE_SALE OS
ON PD.PRODUCT_ID = OS.PRODUCT_ID
GROUP BY OS.PRODUCT_ID
ORDER BY SALES DESC , PRODUCT_CODE;
