SELECT CATEGORY, PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT FR1
WHERE PRICE IN (SELECT MAX(PRICE) FROM FOOD_PRODUCT FR2 GROUP BY CATEGORY HAVING  FR1.CATEGORY = FR2.CATEGORY)
GROUP BY CATEGORY
HAVING CATEGORY IN ('국','김치','식용유','과자')
ORDER BY PRICE DESC