-- 코드를 입력하세요
SELECT
    AP.APNT_NO,
    PI.PT_NAME,
    PI.PT_NO,
    AP.MCDP_CD,
    DC.DR_NAME,
    AP.APNT_YMD
FROM APPOINTMENT AS AP
INNER JOIN PATIENT AS PI
ON PI.PT_NO = AP.PT_NO
INNER JOIN DOCTOR  AS DC
ON DC.DR_ID = AP.MDDR_ID
WHERE date_format(AP.APNT_YMD,'%Y-%m-%d') = '2022-04-13'
AND AP.APNT_CNCL_YMD is null
AND AP.APNT_CNCL_YN = 'N'
ORDER BY AP.APNT_YMD ASC