-- 코드를 입력하세요
SELECT CCC.CAR_ID, CCC.CAR_TYPE,ROUND(CCC.DAILY_FEE * (1-CCD.DISCOUNT_RATE/100)*30) as FEE
FROM CAR_RENTAL_COMPANY_CAR  CCC
INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY CCH
ON CCC.CAR_ID = CCH.CAR_ID
INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN  CCD
ON CCC.CAR_TYPE = CCD.CAR_TYPE
WHERE CCC.CAR_TYPE LIKE '세단' OR 'SUV'
AND CCH.START_DATE >= '2022-11-1' AND CCH.END_DATE <= '2022-11-30'
AND CCD.DURATION_TYPE like "%30일%"
GROUP BY CCC.CAR_ID    
HAVING FEE >= 500000 AND FEE < 2000000
order by FEE desc, CCC.CAR_TYPE, CCC.CAR_ID;


-- 코드를 입력하세요
WITH TEMP AS (
            SELECT A.CAR_ID
                  ,A.CAR_TYPE
                  ,A.DAILY_FEE
            FROM CAR_RENTAL_COMPANY_CAR A 
            INNER JOIN (
                        SELECT CAR_ID
                        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                        GROUP BY CAR_ID 
                        HAVING MAX(END_DATE) <='2022-11-01'
            )  AS B ON A.CAR_ID = B.CAR_ID
            WHERE A.CAR_TYPE IN('세단','SUV')
              )
SELECT B.CAR_ID
      ,A.CAR_TYPE
      ,ROUND(B.DAILY_FEE * (1-A.DISCOUNT_RATE/100)*30) AS FEE
FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS A
INNER JOIN TEMP B ON A.CAR_TYPE = B.CAR_TYPE
WHERE DURATION_TYPE LIKE '%30%'         
AND B.DAILY_FEE*(1-A.DISCOUNT_RATE/100)*30 BETWEEN '500000' 
                                           AND '2000000'
ORDER BY 3 DESC, 2 ASC, 1 DESC