SELECT 
  MP.MEMBER_NAME, 
  RR.REVIEW_TEXT, 
  DATE_FORMAT(RR.REVIEW_DATE,'%Y-%m-%d')
FROM 
  MEMBER_PROFILE MP
JOIN 
  REST_REVIEW RR ON MP.MEMBER_ID = RR.MEMBER_ID
WHERE 
  MP.MEMBER_ID = (
    -- 가장 많은 리뷰를 작성한 회원의 ID를 찾는 서브쿼리
    SELECT  MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY COUNT(*) DESC
    limit 1
  )
ORDER BY 
  RR.REVIEW_DATE ASC, 
  RR.REVIEW_TEXT ASC;