-- 코드를 입력하세요
SELECT CONCAT("/home/grep/src/", USB.BOARD_ID, "/", UGF.FILE_ID, UGF.FILE_NAME, UGF.FILE_EXT) FILE_PATH
FROM USED_GOODS_BOARD USB
INNER JOIN USED_GOODS_FILE  UGF 
ON USB.BOARD_ID = UGF.BOARD_ID
WHERE USB.VIEWS = (
 SELECT MAX(VIEWS)
 FROM USED_GOODS_BOARD 
)
ORDER BY UGF.FILE_ID DESC;