-- 코드를 입력하세요
SELECT ah.AUTHOR_ID, ah.AUTHOR_NAME,bk.CATEGORY,SUM(bk.PRICE * bs.SALES) TOTAL_SALES
FROM BOOK bk
INNER JOIN BOOK_SALES  bs
on bk.BOOK_ID = bs.BOOK_ID
INNER JOIN AUTHOR ah
on ah.AUTHOR_ID = bk.AUTHOR_ID
WHERE  bs.SALES_DATE LIKE '2022-01%'
GROUP BY ah.AUTHOR_NAME,ah.AUTHOR_NAME,bk.CATEGORY
ORDER BY ah.AUTHOR_ID, bk.CATEGORY DESC;